### ISSUE TITLE
multisig

### ISSUE THREAD

**Issue by kodty** [NemProject/NEMAndroidApp#181]
phone make/model: sony xperia c1905
android version: 4.1.2
kernal: 3.4.0

i cannot get into multisig set up at all until iv sent a transaction. when the account is empty or funded it gives the warning about the public key.. it only allows me to enter once i have sent a tx. for the uninitiated, they will not know that they must first send a transaction in order to access multisig for a given account. perhaps it would be better to change the warning to tell users to make a transaction before accessing the multisig set up page.

**Comment by fyahfox** [comment]
I just checked with 1.0.49 and didn't have that problem.

- I made 3 new accounts (multisig, cosigner1, cosigner2)
- I sent some funds to account "multisig"
- I converted the account "multisig" to multisig with accounts "cosigner1" and "cosigner" as cosigners.
- It worked -> I guess the app now checks if the pub keys are known (which is the case because the accounts are in the local wallet).

But still, the error message should be more clear in case people are trying to add an address as cosigner and the according pub key is not known.
What exactly is the error message? I'm not sure which string we have to edit.
