### ISSUE TITLE
Incorrect POI Symbol 

### ISSUE THREAD

**Issue by fiazk** [NemProject/NEMAndroidApp#222]
The app shows a vertical rectangle instead of displaying the POI symbol ‱. Please see image below.

![photo_2016-06-15_15-37-54](https://cloud.githubusercontent.com/assets/17099341/16081752/2147abc6-330f-11e6-88a4-61242908ed40.jpg)

NEM Address: NDAZM2-KCD2XB-4Y7XMM-J5UUZ3-2ZCBHE-MHRHF4-3U3W
Mobile: Samsung Galaxy S3
NEM version 1.0.49

**Comment by nikhiljha** [comment]
Looks like it's fixed in Android 6.0.

For older versions of Android we need to hardcode it into the Java code so that the ‱ shows up correctly.

If someone else working on this project wants to, this needs to be added to the activity through the Java code like this:

final String poiSymbol = "\u2031"

Either that or there isn't font support, so you should probably try that first.

**Comment by fyahfox** [comment]
No problems with the symbol on my Honor 5x, Android 5.1.1.

@am4n0w4r any idea why this happens on some phones?

**Comment by fyahfox** [comment]
https://github.com/NemProject/NEMAndroidApp/issues/194
