### ISSUE TITLE
"No valid server" "Server error occurred" when app started

### ISSUE THREAD

**Issue by fiazk** [NemProject/NEMAndroidApp#241]
When app started I get the issue displayed below. I have tried the 1st two defaulted servers and I get these errors, however, the third server works just fine. I tried killing the app and start over again but nothing happened. 
![photo_2016-08-12_13-17-03](https://cloud.githubusercontent.com/assets/17099341/17620829/5cdd7e1a-608f-11e6-87e9-79abfb20149a.jpg)
![photo_2016-08-12_13-16-52](https://cloud.githubusercontent.com/assets/17099341/17620830/5ce180b4-608f-11e6-8f7b-acda97123154.jpg)
![photo_2016-08-12_13-16-46](https://cloud.githubusercontent.com/assets/17099341/17620831/5ce4af64-608f-11e6-884f-8a88ac0ed955.jpg)
![photo_2016-08-12_13-18-54](https://cloud.githubusercontent.com/assets/17099341/17620832/5ce9c206-608f-11e6-970d-0aa9879d1363.jpg)

Mobile: Samsung S3
Android 4.3
NEM 1.0.53

NDAZM2-KCD2XB-4Y7XMM-J5UUZ3-2ZCBHE-MHRHF4-3U3W

**Comment by fiazk** [comment]
@fyahfox @jabo38 this it's extremely annoying because the app automatically changes the server to the 1st which doesn't work "artygeek.net" and I have to manually change it every time

**Comment by jabo38** [comment]
@am4n0w4r is there a reason why the app is connecting to bad servers?

**Comment by am4n0w4r** [comment]
The app uses heartbeat as the quickest and simplest way to determine if server is working.
"Server error occurred" means that heartbeat to that server passed ok but somehow server returns bad result for other requests.
Please send commented log report right after this happens and write the time when you did it here so I can investigate a little bit what's happening.

**Comment by am4n0w4r** [comment]
I've tested this behavior on old emulator which have old non-working servers. This behavior is reproducible and the reasons are like I described - server that appears to be the fastest, cannot handle transaction requests. The simplest way is to delete that server from list because it seems that it usually happens on old servers that are not updated. Otherwise we need to change the criteria by which app can consider server as working and change detection logic, e.g. take into account not only the fastest response but latest errors count from that server, or something like that

**Comment by jabo38** [comment]
While on the testnet this is a problem because some people don't update their servers, on the mainnet version it should be fine because our suggested servers should be good.  So we can think about fixing this later and should note it is a problem, but it is not urgent.

**Comment by jabo38** [comment]
bounty paid Transaction hash: 218e346e5041ffb703ae6a3486585fed5187e68db4f8a4b90ec004346e650f43
